### PR TITLE
Updated dependencies and bumped the version

### PR DESCRIPTION
**Pull request by enobayram**
This PR updates the code to compile with GHC 8.2.2 and more modern versions of the dependencies. Updating Servant in particular caused a significant amount of diff.

### CODE REVIEW

**Comment by utdemir** [comment]
Hey. Thank you for your PR :). As you can see, I wasn't actively maintaining this project, so CI stuff and a few other things are a bit out of date, sorry. 

I am going to spend a bit of time fixing CI, then merge your changes.

**Comment by enobayram** [comment]
Thanks :) I might open occasional PRs as we periodically update our dependencies.

**Comment by utdemir** [comment]
Thank you @enobayram, merged. 

Have a nice day and say hi to Picus development team :) .

**Comment by utdemir** [comment]
Released: https://hackage.haskell.org/package/pivotal-tracker-0.2.0.0

**Comment by frontsideair** [comment]
🥂

**Comment by enobayram** [comment]
Thanks! 
> Say hi to Picus development team :) 

I did :) 

Have a nice day!

**Pull request merged**
